include:
  - project: flywheel-io/tools/etc/qa-ci
    file: ci/lib.yml
    ref: c36806cde04141d414cbd28d50255e93b41e0f9d

variables:
  PYVER: "3.9"
  PYTEST_COV_FAIL_UNDER: 0  # Set pytest coverage to 0
  DEBUG: "" # Set debug mode to print out executed command on qa-ci
