repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: 3f844e260bdc9114ecd14ffeae7b917f85acaf62
    hooks:
      - id: poetry_export
     #  - id: generate_docs # not available yet
     #   args: [docker_run, build] # mkdocs not available yet
      - id: yamllint
      - id: ruff
        args: [
          --ignore, "F403,E402",
          --fix
        ]
      - id: pytest
